[program:madaba-laravel-scheduler]
process_name=%(program_name)s
command=php /var/www/madaba_mfi/artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/madaba_mfi/storage/logs/scheduler.log
stopwaitsecs=3600
